"""Create retry policies table

Revision ID: 2efd3a0148b8
Revises: 288e10d49c07
Create Date: 2026-07-10 18:49:07.217240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efd3a0148b8'
down_revision: Union[str, Sequence[str], None] = '288e10d49c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retry_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('initial_delay', sa.Integer(), nullable=True),
    sa.Column('max_delay', sa.Integer(), nullable=True),
    sa.Column('backoff_multiplier', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_policies_id'), 'retry_policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retry_policies_id'), table_name='retry_policies')
    op.drop_table('retry_policies')
    # ### end Alembic commands ###
