"""add job idempotency key

Revision ID: ae3590e65ced
Revises: f0e5f2b2b4c2
Create Date: 2026-07-12 17:25:56.697408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae3590e65ced'
down_revision: Union[str, Sequence[str], None] = 'f0e5f2b2b4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###
